Repository puppetlabs/vmpooler-deployment, pull requests merged in 2023-08, with the labels that each got.

#110 Bump jruby and all vmpooler gems
  docker/Dockerfile
  docker/Dockerfile.local
  docker/Gemfile.lock
Labels: enhancement

#108 (RE-15638) Make redis connection options configurable
  helm-charts/vmpooler/templates/deployment-manager.yaml
  helm-charts/vmpooler/values.yaml
Labels: enhancement

#111 3.2.0 release prep
  CHANGELOG.md
  docs/index.yaml
  docs/vmpooler-3.2.0.tgz
  helm-charts/vmpooler/Chart.yaml
Labels: maintenance

#113 (RE-15696) Improve development experience
  .gitignore
  README.md
  docker/.dockerignore
  docker/.rerun
  docker/Dockerfile
  docker/Dockerfile.dev
  docker/Gemfile.dev
  docker/Gemfile.local
  docker/data/vmpooler.yaml
  docker/docker-compose.dev.yml
  docker/docker-entrypoint.dev.sh
  docker/vmpooler.yaml
Labels: enhancement

#116 3.3.0 release prep
  CHANGELOG.md
  docs/index.yaml
  docs/vmpooler-3.3.0.tgz
  helm-charts/vmpooler/Chart.yaml
Labels: maintenance

#117 Fix 3.3.0 in changelog
  CHANGELOG.md
Labels: maintenance

#124 (maint) Update vmpooler to 3.4.0, vmpooler-provider-gce to 1.3.0, and…
  docker/Gemfile.lock
Labels: enhancement

#126 (maint) Release prep for 3.4.0
  CHANGELOG.md
  docs/index.yaml
  docs/vmpooler-3.4.0.tgz
  helm-charts/vmpooler/Chart.yaml
Labels: maintenance

#127 (maint) Fix changelog for vmpooler 3.4.0 release
  CHANGELOG.md
Labels: maintenance

#129 (RE-15710) Bump vmpooler-provider-vsphere gem to 3.3.1
  docker/Gemfile.lock
Labels: bug

#130 3.4.1 release prep
  CHANGELOG.md
  docs/index.yaml
  docs/vmpooler-3.4.1.tgz
  helm-charts/vmpooler/Chart.yaml
Labels: maintenance

#131 (maint) Update vmpooler to 3.5.0 and vmpooler-provider-vsphere to 3.3.2
  docker/Gemfile.lock
Labels: enhancement

#132 (maint) Release prep for version 3.5.0
  CHANGELOG.md
  docs/index.yaml
  docs/vmpooler-3.5.0.tgz
  helm-charts/vmpooler/Chart.yaml
Labels: maintenance

#135 (maint) Bump vmpooler gem to 3.5.1
  docker/Gemfile.lock
Labels: bug

#134 (maint) Release prep for version 3.5.1
  CHANGELOG.md
  docs/index.yaml
  docs/vmpooler-3.5.1.tgz
  helm-charts/vmpooler/Chart.yaml
Labels: maintenance

#137 (maint) Update vmpooler-provider-vsphere to 3.3.3
  docker/Gemfile.lock
Labels: bug

#138 (maint) Release prep for version 3.5.2
  CHANGELOG.md
  docs/index.yaml
  docs/vmpooler-3.5.2.tgz
  helm-charts/vmpooler/Chart.yaml
Labels: maintenance

#139 (maint) Update vmpooler-provider-vsphere to 3.3.4
  docker/Gemfile.lock
Labels: bug
