Repository puppetlabs/vmpooler-deployment, pull requests merged in 2023-10, with the labels that each got.

#144 (RE-15163) Call BGREWRITEAOF on the redis database every restart to reduce aof file size
  helm-charts/vmpooler/values.yaml
Labels: bug

#145 Gem dependency updates
  docker/Gemfile.lock
Labels: enhancement

#146 3.7.0 release prep
  CHANGELOG.md
  docs/index.yaml
  docs/vmpooler-3.7.0.tgz
  helm-charts/vmpooler/Chart.yaml
Labels: maintenance

#147 (RE-15696) Local Development - Add Grafana and remove redis mount
  .gitignore
  README.md
  docker/data/redis/.gitkeep
  docker/docker-compose.dev.yml
  docker/docker-compose.yml
  docker/grafana/provisioning/datasources/datasource.yml
  docker/prometheus.yml
Labels: enhancement
